//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_AplicacionEjemploEntities : DbContext
    {
        public BD_AplicacionEjemploEntities()
            : base("name=BD_AplicacionEjemploEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VPersonas> V_Personas { get; set; }
    
        public virtual int SP_Mantenimiento_Personas(string p_accion, string p_cedula, string p_nombre, string p_apellidos, string p_telefono, string p_direccion)
        {
            var p_accionParameter = p_accion != null ?
                new ObjectParameter("p_accion", p_accion) :
                new ObjectParameter("p_accion", typeof(string));
    
            var p_cedulaParameter = p_cedula != null ?
                new ObjectParameter("p_cedula", p_cedula) :
                new ObjectParameter("p_cedula", typeof(string));
    
            var p_nombreParameter = p_nombre != null ?
                new ObjectParameter("p_nombre", p_nombre) :
                new ObjectParameter("p_nombre", typeof(string));
    
            var p_apellidosParameter = p_apellidos != null ?
                new ObjectParameter("p_apellidos", p_apellidos) :
                new ObjectParameter("p_apellidos", typeof(string));
    
            var p_telefonoParameter = p_telefono != null ?
                new ObjectParameter("p_telefono", p_telefono) :
                new ObjectParameter("p_telefono", typeof(string));
    
            var p_direccionParameter = p_direccion != null ?
                new ObjectParameter("p_direccion", p_direccion) :
                new ObjectParameter("p_direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Mantenimiento_Personas", p_accionParameter, p_cedulaParameter, p_nombreParameter, p_apellidosParameter, p_telefonoParameter, p_direccionParameter);
        }
    }
}
