//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionEjemplo.PersonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VPersonas", Namespace="http://schemas.datacontract.org/2004/07/WcfDatos")]
    [System.SerializableAttribute()]
    public partial class VPersonas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonService.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/FindAll", ReplyAction="http://tempuri.org/IPersonService/FindAllResponse")]
        AplicacionEjemplo.PersonService.VPersonas[] FindAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/FindAll", ReplyAction="http://tempuri.org/IPersonService/FindAllResponse")]
        System.Threading.Tasks.Task<AplicacionEjemplo.PersonService.VPersonas[]> FindAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/Find", ReplyAction="http://tempuri.org/IPersonService/FindResponse")]
        AplicacionEjemplo.PersonService.VPersonas Find(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/Find", ReplyAction="http://tempuri.org/IPersonService/FindResponse")]
        System.Threading.Tasks.Task<AplicacionEjemplo.PersonService.VPersonas> FindAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/Encontrar", ReplyAction="http://tempuri.org/IPersonService/EncontrarResponse")]
        AplicacionEjemplo.PersonService.VPersonas[] Encontrar(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/Encontrar", ReplyAction="http://tempuri.org/IPersonService/EncontrarResponse")]
        System.Threading.Tasks.Task<AplicacionEjemplo.PersonService.VPersonas[]> EncontrarAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditPerson", ReplyAction="http://tempuri.org/IPersonService/EditPersonResponse")]
        int EditPerson(string accion, string cedula, string nombre, string apellidos, string telefono, string direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditPerson", ReplyAction="http://tempuri.org/IPersonService/EditPersonResponse")]
        System.Threading.Tasks.Task<int> EditPersonAsync(string accion, string cedula, string nombre, string apellidos, string telefono, string direccion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : AplicacionEjemplo.PersonService.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<AplicacionEjemplo.PersonService.IPersonService>, AplicacionEjemplo.PersonService.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AplicacionEjemplo.PersonService.VPersonas[] FindAll() {
            return base.Channel.FindAll();
        }
        
        public System.Threading.Tasks.Task<AplicacionEjemplo.PersonService.VPersonas[]> FindAllAsync() {
            return base.Channel.FindAllAsync();
        }
        
        public AplicacionEjemplo.PersonService.VPersonas Find(string id) {
            return base.Channel.Find(id);
        }
        
        public System.Threading.Tasks.Task<AplicacionEjemplo.PersonService.VPersonas> FindAsync(string id) {
            return base.Channel.FindAsync(id);
        }
        
        public AplicacionEjemplo.PersonService.VPersonas[] Encontrar(string id) {
            return base.Channel.Encontrar(id);
        }
        
        public System.Threading.Tasks.Task<AplicacionEjemplo.PersonService.VPersonas[]> EncontrarAsync(string id) {
            return base.Channel.EncontrarAsync(id);
        }
        
        public int EditPerson(string accion, string cedula, string nombre, string apellidos, string telefono, string direccion) {
            return base.Channel.EditPerson(accion, cedula, nombre, apellidos, telefono, direccion);
        }
        
        public System.Threading.Tasks.Task<int> EditPersonAsync(string accion, string cedula, string nombre, string apellidos, string telefono, string direccion) {
            return base.Channel.EditPersonAsync(accion, cedula, nombre, apellidos, telefono, direccion);
        }
    }
}
